### PR TITLE
fixed: background video recording

### PR DESCRIPTION
**Pull request by s0llvan**
- Fixed video recording in the background
- Added button on the notification to stop the video recording
- Added click on the notification to open the application

It should be noted that when closing the application, there is a brief interruption in the video recording. The same happens when opening the application if a recording is in progress. This is due to the preview.

This is a major refactor, so there may be oversights or errors on my part, even though I did not encounter any issues during my tests.

These modifications have been tested on Android 14 and Android 9.

#43

### CODE REVIEW

**Comment by anonfaded** [comment]
Hmm
I would suggest that you make apk builds and attach that apk to your fork of FadCam (in releases) on every Pull Request you make, so i can download and test on my Android 11 too.

**Comment by s0llvan** [comment]
> Hmm I would suggest that you make apk builds and attach that apk to your fork of FadCam (in releases) on every Pull Request you make, so i can download and test on my Android 11 too.

Unfortunately, you cannot upload APKs in the comments on GitHub, but you should be able to test the pull request locally: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally.

**Comment by anonfaded** [comment]
> Unfortunately, we cannot upload APKs in the comments on GitHub, but you should be able to test the pull request locally: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally.

hmm i read that, but its easier if you make apk and attach that to your releases. I didn't meant to add apk in comments.
See in the screenshot there is option in ur fork. When u build the apk(unsigned) in android studio, you can just upload it to your releases.
image

**Comment by s0llvan** [comment]
> > Unfortunately, we cannot upload APKs in the comments on GitHub, but you should be able to test the pull request locally: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally.
> 
> hmm i read that, but its easier if you make apk and attach that to your releases. I didn't meant to add apk in comments. See in the screenshot there is option in ur fork. When u build the apk(unsigned) in android studio, you can just upload it to your releases. image

Oh ok, if you want [FadCam v1.2.0 beta](https://github.com/s0llvan/FadCam/releases/tag/v1.2.0-beta)

**Comment by anonfaded** [comment]
Yeah always replace this apk with ur latest commits so i can check faster.

Btw right now the notification feature is buggy. The stop button stops the video but when i click on notification, it opens the app but stops the video and again i see the toast msg that video started. Also sometimes it crashes the app so its not working.

**Comment by s0llvan** [comment]
> Yeah always replace this apk with ur latest commits so i can check faster.
> 
> Btw right now the notification feature is buggy. The stop button stops the video but when i click on notification, it opens the app but stops the video and again i see the toast msg that video started. Also sometimes it crashes the app so its not working.
> 
> 

I also have errors with Android 11, I will fix that and then run tests on other versions as well.

**Comment by s0llvan** [comment]
The message indicating that the video has started is normal, but it doesn't mean that the video is stopped. I think it's better to remove it if the recording is already in progress.
Can you share the crash logs please, because I can't reproduce the crash 😕

But i found another issue : H.265 encoder is not compatible with all phones, which is causing additional errors.

**Comment by anonfaded** [comment]
> The message indicating that the video has started is normal, but it doesn't mean that the video is stopped. I think it's better to remove it if the recording is already in progress.
> Can you share the crash logs please, because I can't reproduce it 😕

ok i will try, btw i was getting that toast message that recording has started but the video wasnt stopped.



> But i found another issue : H.265 encoder is not compatible with all phones, which is causing additional errors.

oh but it works on most phones so how its not supported on some phones? If this is a confirmed issue then we need to have a spinner option for this too in settings so user can choose which encoder they want, and we can add that info card below it explaining the issue.

**Comment by s0llvan** [comment]
Normally, it’s supported by all phones, yes, strange... we'll see if a spinner is needed.

I made a small fix, and I’m continuing to test to try to find others and reproduce the one you reported. Don’t hesitate to let me know if the bug has disappeared or not.

**Comment by anonfaded** [comment]
There are weird issues still in the app.
Sometimes clicking on stop button stops but when i open the camera its still recording. Or sometimes it takes too long to stop the video. So what's the actual issue?
See the screenshot below, when i pressed stop in notification nothing happened and video was still recording


And now even the file names are not correct:



So try to fix it or we can remove this feature for now.

Btw i was working on a basic website for FadCam here https://fadcam.fadedhood.com

**Comment by Chip3211** [comment]
I successfully recorded 4+ hours so this issue seems to be fixed. However a few new bugs were introduced as @anonfaded  already mentioned.

When stopping a video, the app crashes if I try to start a new recording while the previous one is still being post processed.
Is post processing, instead of renaming the file, even necessary if I disabled all watermark options?

**Comment by anonfaded** [comment]
> I successfully recorded 4+ hours so this issue seems to be fixed. However a few new bugs were introduced as @anonfaded  already mentioned.
> 
> When stopping a video, the app crashes if I try to start a new recording while the previous one is still being post processed.
> Is post processing, instead of renaming the file, even necessary if I disabled all watermark options?

You recorded for 4 hours with 'no watermark' ?
Right now the watermarking takes very long bcz it adds the watermark in every frame of video, while in 'no watermark' option this doesn't happen, instead the temp video is directly copied to records section.
The watermarking time will be decreased when i change the logic and instead use a subtitle file and combine it with the video. But right now there are other bugs which should be fixed first.

**Comment by s0llvan** [comment]
> There are weird issues still in the app. Sometimes clicking on stop button in notification stops the video but when i open the app it's still recording. Or sometimes it takes too long to stop the video. So what's the actual issue? See the screenshot below, when i pressed stop in notification nothing happened and video was still recording for few seconds then it stopped
> 
> 
> 
> And now even the file names are not correct: 
> 
> So try to fix it or we can remove this feature for now.
> 
> Btw i was working on a basic website for FadCam here https://fadcam.fadedhood.com

I'm trying to solve these issues, but it's complicated because sometimes I manage to reproduce a bug, and then the bug disappears...

Nice website, by the way.

**Comment by anonfaded** [comment]
> I'm trying to solve these issues, but it's complicated because sometimes I manage to reproduce a bug, and then the bug disappears...\n\nNice website, by the way.

Weird bug. I asked another user on discord, he recorded for 40 minutes i guess and then the notification disappeared and recording stopped, and app crashes too as he said. While other person here said he recorded for 4 hours.

And thanks, website is all made by Ai haha

**Comment by anonfaded** [comment]
User said that recorded stopped at 29minutes and the video was stuck afterwards

**Comment by s0llvan** [comment]
Is it the version I provided that he is using ?

There's something I don't understand in the code : why use ffmpeg to copy the file when there is no watermark instead of directly creating the final file ?

**Comment by anonfaded** [comment]
> Is it the version I provided that he is using ?
> 
> There's something I don't understand in the code : why use ffmpeg to copy the file when there is no watermark instead of directly creating the final file ?

Oh wait, i gave him my apk lolllll blunder mistake🤣
I forgot to give him ur apk build.
Will shark link with him again.

And the ffmpeg thing i used at that time just to simplify the process as i was in hurry.

We will make this faster and better as i already said before. With that we will need to tweak other functions too like the video naming and all that. Right now first a video is saved with temp_ prefix and then after watermarking process, it is changed into FADCAM_ prefix, and temp video is deleted.
But for no watermark, it copies that same temp video and do the process. So this is another work with lower priority, first we need this issue fixed where Fadcam text is double applied to video which is saved, and notification etc.

I'll let other users to install ur apk and then share feedback, untill then we have to wait.

**Comment by Chip3211** [comment]
> Is it the version I provided that he is using ?
> 
> There's something I don't understand in the code : why use ffmpeg to copy the file when there is no watermark instead of directly creating the final file ?

Thats the same thing I asked earlier.
I looked up the difference between copying with ffmpeg and just renaming the file.
You can remux the output and fix fragmented or broken metadata when copying with ffmpeg.
The question is if we need that type of action since we don’t change the extension and video container.

**Comment by s0llvan** [comment]
> Thats the same thing I asked earlier.
> I looked up the difference between copying with ffmpeg and just renaming the file.
> You can remux the output and fix fragmented or broken metadata when copying with ffmpeg.
> The question is if we need that type of action since we don’t change the extension and video container.

Yes, that's also what I noticed, but since we are not currently doing it, I wondered if it was necessary or not.

**Comment by s0llvan** [comment]
The issue with the file name came from the double call to stopRecording, and I think the crash when stopping the recording was also caused by the same thing.

Feel free to let me know if these two problems are fixed on your side as well.

**Comment by anonfaded** [comment]
> The issue with the file name came from the double call to stopRecording, and I think the crash when stopping the recording was also caused by the same thing.
> 
> Feel free to let me know if these two problems are fixed on your side as well.

will test ur apk right now

**Comment by s0llvan** [comment]
I just found a few more bugs, I'll fix them.

**Comment by anonfaded** [comment]
> I just found a few more bugs, I'll fix them.

Okay, then I'll test later today and will ask other user to test too

**Comment by s0llvan** [comment]
It still needs a bit of optimization that I'm working on, but with the last fix I'm committing, I haven't found any other bugs.

**Comment by anonfaded** [comment]
You replaced the recording codec with old one? H124 something?
If yes, we will need to test the video quality then as i have reduced bitrate by 50% for the HEVC to use less space as someone asked for it. which u said isn't supported on some phones

**Comment by s0llvan** [comment]
> You replaced the recording codec with old one? H124 something? If yes, we will need to test the video quality then as i have reduced bitrate by 50% for the HEVC to use less space as someone asked for it. which u said isn't supported on some phones

That was my mistake, it's just that H265 doesn't work for me, but I modified the commit with a force push to undo it

**Comment by anonfaded** [comment]
Today the link of ur apk i shared with a user, he tested and said that recording stopped after 29seconds while voice was recorded for 1+ hour. So it seems like the issue isn't fixed.

Also can you be active in the discord too so you will know urself from the beta testers

**Comment by s0llvan** [comment]
> Today the link of ur apk i shared with a user, he tested and said that recording stopped after 29seconds while voice was recorded for 1+ hour. So it seems like the issue isn't fixed.
> 
> Also can you be active in the discord too so you will know urself from the beta testers

It's weird that it works for me and for @Chip3211 but not for him... does it work for you ?
I'm going to try going on Discord

**Comment by anonfaded** [comment]
> > Today the link of ur apk i shared with a user, he tested and said that recording stopped after 29seconds while voice was recorded for 1+ hour. So it seems like the issue isn't fixed.
> > 
> > Also can you be active in the discord too so you will know urself from the beta testers
> 
> It's weird that it works for me and for @Chip3211 but not for him... does it work for you ?
> I'm going to try going on Discord

I'll test but my Android version is 11 not 14 as main issue is for versions above 11. You can ask that user on discord to better understand.

**Comment by anonfaded** [comment]
Why most of commits are just copy paste of same old code?

**Comment by s0llvan** [comment]
> Why most of commits are just copy paste of same old code?

I'm not sure I understand... because the code that was in the HomeFragment was working fine ?

**Comment by anonfaded** [comment]
> > Why most of commits are just copy paste of same old code?
> 
> I'm not sure I understand... because the code that was in the HomeFragment was working fine ?

I mean in some commits i see that some existing codeblocks are marked as removed in red color while below in that file, the exact same codeblocks without any addition are all green and re-added. Well it's ok, i was just wondering, maybe its bcz of IDE or something which marks them like that.

**Comment by s0llvan** [comment]
> > > Why most of commits are just copy paste of same old code?
> > 
> > 
> > I'm not sure I understand... because the code that was in the HomeFragment was working fine ?
> 
> I mean in some commits i see that some existing codeblocks are marked as removed in red color while below in that file, the exact same codeblocks without any addition are all green and re-added. Well it's ok, i was just wondering, maybe its bcz of IDE or something which marks them like that.

It’s possible that it’s the IDE, for imports for example, it sorts them, but if it’s not for imports, I would be curious to see an example ^^

**Comment by anonfaded** [comment]
> It’s possible that it’s the IDE, for imports for example, it sorts them, but if it’s not for imports, I would be curious to see an example ^^

In recent commits now it isn't showing, but I'll try to find lol it was like for example 500-- and at the same time 500++

**Comment by s0llvan** [comment]
> > It’s possible that it’s the IDE, for imports for example, it sorts them, but if it’s not for imports, I would be curious to see an example ^^
> 
> In recent commits now it isn't showing, but I'll try to find lol it was like for example 500-- and at the same time 500++

Okay, strange 😶

**Comment by SyntevoAlex** [comment]
@s0llvan and others, could you please clarify (in technical terms) what exactly was wrong with background recording?

I'm struggling with it for a month or so already. My issue is that on Xiaomi Redmi 13C, background recording only lasts for 40-45 minutes (slightly random duration each time) and then suddenly stops, leaving `tmp*.mp4` video file. I already tried all sorts of phone settings, to no avail. I'm using FadCam 1.1.3, therefore without this PR.

So far my only success in investigation was that `logcat` has the following each time recording suddenly stops:
```
11-24 14:09:32.399  1547  1594 W UsageStatsService: Unexpected activity event reported! (com.fadcam/com.fadcam.MainActivity event : 23 instanceId : 80625181)
11-24 14:09:32.402  1547  1809 I CameraOpt_CameraBooster: notify3rdCameraForegroundState isCameraForeground: false, caller : com.fadcam
...
11-24 14:09:33.079 15143 15143 W Activity: PerfMonitor: Slow Operation: Activity com.fadcam/.MainActivity onDestroy took 678ms
11-24 14:09:33.080  1547  5135 D CoreBackPreview: Window{49675c8 u0 com.fadcam/com.fadcam.MainActivity}: Setting back callback null
11-24 14:09:33.147  1547  5135 D WindowManager: setParent old=ActivityRecord{96720c7 u0 com.fadcam/.MainActivity t875},new=null,this window=Window{49675c8 u0 com.fadcam/com.fadcam.MainActivity},callers=
	com.android.server.wm.WindowContainer.removeChild:831 
	com.android.server.wm.ActivityRecord.removeChild:5163 
	com.android.server.wm.ActivityRecord.removeChild:458 
	com.android.server.wm.WindowContainer.removeImmediately:889 
	com.android.server.wm.WindowState.removeImmediately:2490 
	com.android.server.wm.WindowState.removeIfPossible:2662
```

And I tracked `UsageStatsService: Unexpected activity event reported!` string to `com.android.server.usage#reportEvent()` :
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/usage/java/com/android/server/usage/UsageStatsService.java;l=1123

**Comment by anonfaded** [comment]
> @s0llvan and others, could you please clarify (in technical terms) what exactly was wrong with background recording?
> 
> I'm struggling with it for a month or so already. My issue is that on Xiaomi Redmi 13C, background recording only lasts for 38-46 minutes (slightly random duration each time) and then suddenly stops, leaving `tmp*.mp4` video file. I already tried all sorts of phone settings, to no avail. I'm using FadCam 1.1.3, therefore without this PR.
> 
> So far my only success in investigation was that `logcat` has the following each time recording suddenly stops:
> ```
> 11-24 14:09:32.399  1547  1594 W UsageStatsService: Unexpected activity event reported! (com.fadcam/com.fadcam.MainActivity event : 23 instanceId : 80625181)
> 11-24 14:09:32.402  1547  1809 I CameraOpt_CameraBooster: notify3rdCameraForegroundState isCameraForeground: false, caller : com.fadcam
> ...
> 11-24 14:09:33.079 15143 15143 W Activity: PerfMonitor: Slow Operation: Activity com.fadcam/.MainActivity onDestroy took 678ms
> 11-24 14:09:33.080  1547  5135 D CoreBackPreview: Window{49675c8 u0 com.fadcam/com.fadcam.MainActivity}: Setting back callback null
> 11-24 14:09:33.147  1547  5135 D WindowManager: setParent old=ActivityRecord{96720c7 u0 com.fadcam/.MainActivity t875},new=null,this window=Window{49675c8 u0 com.fadcam/com.fadcam.MainActivity},callers=
> 	com.android.server.wm.WindowContainer.removeChild:831 
> 	com.android.server.wm.ActivityRecord.removeChild:5163 
> 	com.android.server.wm.ActivityRecord.removeChild:458 
> 	com.android.server.wm.WindowContainer.removeImmediately:889 
> 	com.android.server.wm.WindowState.removeImmediately:2490 
> 	com.android.server.wm.WindowState.removeIfPossible:2662
> ```
> 
> And I tracked `UsageStatsService: Unexpected activity event reported!` string to `com.android.server.usage#reportEvent()` :
> https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/usage/java/com/android/server/usage/UsageStatsService.java;l=1123

Hi 👋🏻 
The issue was only a single permission that was missing in the Android manifest file.

And this issue is fixed in version above 1.1.3, you are using the one from F-Droid and that is outdated. For now, the latest version is only available at GitHub so please download the latest beta version from the releases section and your issue will be solved😀 
Letme know when you test it.

**Comment by SyntevoAlex** [comment]
Could you please tell me which permission is that?

I tested, and for the first time, I was able to record a video 4 hrs straight! Hooray! Big thanks to anyone who made this possible

**Comment by anonfaded** [comment]
> Could you please tell me which permission is that?
> 
> I tested 1.2.0 from GitHub, and for the first time, I was able to record a video 4 hrs straight until stopped it myself! Hooray! Big thanks to everyone who made this possible

Yeah, i checked another open source app and found that they were using foreground service microphone permission. So without this permission, the app worked fine for Android 11 and below, but for above versions this permission was must due to strict android restrictions. So when i tried this, it worked. The link to permission code:
https://github.com/anonfaded/FadCam/blob/master/app%2Fsrc%2Fmain%2FAndroidManifest.xml#L43


And good to know that now it's fine for you:)
The latest version of app has alot of improvements like battery optimization disabling, wake lock etc. 
To know all the improvements, please read the release note here:
https://github.com/anonfaded/FadCam/releases/tag/v1.2.0

As you mentioned you already are using 1.2.0 now, so in the 1.2.1-beta there is one more feature which is a new "flashlight 🔦" button.
If you want to stay updated then optionally you can join the discord group. Thanks.

**Comment by SyntevoAlex** [comment]
Thanks a lot for your detailed answers!

**Comment by SyntevoAlex** [comment]
Hmm, I can see that `android.permission.FOREGROUND_SERVICE_MICROPHONE` was added in FadCam 1.1.1, and I was using 1.1.3 and had problems which are now gone in 1.2.0. So the problem must have been solved by something else

**Comment by anonfaded** [comment]
> Hmm, I can see that `android.permission.FOREGROUND_SERVICE_MICROPHONE` was added in FadCam 1.1.1, and I was using 1.1.3 and had problems which are now gone in 1.2.0. So the problem must have been solved by something else

Oh I'll recheck in the commits i might be forgetting it now, and will let you know. But i remember that was a permission related to microphone and when i added it, then the issue was solved completely only with that one permission. Like the microphone was being stopped by the android system on latest Android i guess and after this, it was being used without any issue. I'll let you know after confirming it.

Also before this we tried adding wake lock, persistent notification, battery optimization disabling features but still it was being killed by the system. And only that one permission fixed all the headache. Will let you know today.

**Comment by s0llvan** [comment]
> Hmm, I can see that `android.permission.FOREGROUND_SERVICE_MICROPHONE` was added in FadCam 1.1.1, and I was using 1.1.3 and had problems which are now gone in 1.2.0. So the problem must have been solved by something else

Video recording was also moved to a service because there is a risk that Android might put the app to sleep, even if battery optimization is disabled for it. Therefore, it was strongly recommended to place it in a service.

**Pull request merged**
