### PR TITLE
feature: added fps restrictions based on resolution and supported frame rates for the selected camera

### PR DESCRIPTION
**Pull request by s0llvan**
Need tests for 60 and 90 fps like #38

### CODE REVIEW

**Comment by s0llvan** [comment]
> > Need tests for 60 and 90 fps like #38
> 
> Will try this on my device in some moments, and will ask another user to test for 60fps.
> 
> Previously he tested the 60fps option but his recorded video was still recorded in 30fps and not 60, so let's see if this works now.

That's weird...

Could he have tested it in 24 fps, too ?
The resolution he chose supported the 60 fps ?

**Comment by anonfaded** [comment]
> > > Need tests for 60 and 90 fps like #38
> > 
> > Will try this on my device in some moments, and will ask another user to test for 60fps.
> > 
> > Previously he tested the 60fps option but his recorded video was still recorded in 30fps and not 60, so let's see if this works now.
> 
> That's weird...
> 
> Could he have tested it in 24 fps, too ?
> The resolution he chose supported the 60 fps ?

His device supports 60fps. I then asked him to use mediainfo app to check fps and he sent this where it showed 30fps while 60fps was selected.


But we will try this new version, this may work. Idk why it didn't work for him.

**Comment by s0llvan** [comment]
Does it test with the rear camera in FHD ?
I see that only the full HD rear camera is compatible with this device

**Comment by s0llvan** [comment]
Does it test with the rear camera in FHD ? and 24 fps works ?
I see that only the full HD rear camera is compatible with this device

**Pull request merged**
