### PR TITLE
Bad audio quality and missing notifications permission fixed, max camera frame rates refactoring

### PR DESCRIPTION
**Pull request by s0llvan**
#29 fixed with the highest common audio quality, but as discussed, an option to select audio quality is to be foreseen later
#40 partially fixed (the notification does not appear at the first video capture)
#23 (like #39) need tests for 60 and 90 fps

### CODE REVIEW

**Comment by anonfaded** [comment]
Great work 😀
Will merge and test in some moments.

Btw i see your profile has only this repository as a fork and none others, curious to know the reason

**Comment by s0llvan** [comment]
> Great work 😀 Will merge and test in some moments.
> 
> Btw i see your profile has only this repository as a fork and none others, curious to know the reason

Thanks 😁

I created my account in early September 😅 anothers forks coming soon !

**Comment by anonfaded** [comment]
> > Great work 😀 Will merge and test in some moments.
> > 
> > Btw i see your profile has only this repository as a fork and none others, curious to know the reason
> 
> Thanks 😁
> 
> I created my account in early September 😅 anothers forks coming soon !

So was this your first open source contribution?

Also can you share how you got to know about FadCam project? :)

**Comment by s0llvan** [comment]
> > > Great work 😀 Will merge and test in some moments.
> > > Btw i see your profile has only this repository as a fork and none others, curious to know the reason
> > 
> > 
> > Thanks 😁
> > I created my account in early September 😅 anothers forks coming soon !
> 
> So was this your first open source contribution?
> 
> Also can you share how you got to know about FadCam project? :)

By chance ^^, I was looking for a free app, without ads or trackers, to record trips, and I came across FadCam

Yes, this is my first open source contribution, but i'm developer (web) sinced many years.

**Comment by anonfaded** [comment]
Wow, good to know :)
Some users found it on YouTube where content creators featured this app. I didn't expect this much downloads so it all happened so fast and I'm happy that people liked it.

I did some basic web dev, and nowadays doing python for backend, also doing CTFs and learning cyber security as main. Android dev and java just happened very randomly lol

**Comment by s0llvan** [comment]
> Wow, good to know :) Some users found it on YouTube where content creators featured this app. I didn't expect this much downloads so it all happened so fast and I'm happy that people liked it.
> 
> I did some basic web dev, and nowadays doing python for backend, also doing CTFs and learning cyber security as main. Android dev and java just happened very randomly lol

It's cool then, i also train in cybersecurity.
It's true there's already a lot of success for such a recent application 🙂

**Comment by anonfaded** [comment]
Checked, seems fine. Thanks!

**Pull request merged**
